[package]
name = "alfred-pinboard-rs"
version = "0.20.0"
authors = [ "Hamid Ghadyani <hamid@hamid.cc>", "Victor Rodrigues",]
edition = "2021"
description = "Alfred workflow for Pinboard.in bookmarks, written in Rust."
license = "MIT"
repository = "https://github.com/vmlrodrigues/alfred-pinboard-rs"

[dependencies]
alfred = "4.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3.15"
semver = "1.0.4"
thiserror = "1.0"
dirs = "5.0"
log = "0.4"
env_logger = "0.10"

[features]

[dependencies.alfred-rs]
version = "0.7"

[dependencies.rusty-pin]
git = "https://github.com/vmlrodrigues/rusty-pin"
rev = "2681a76009386aac5613e6d842d085afa1af6149"

[dependencies.chrono]
version = "0.4"
features = [ "serde",]

[profile.release]
lto = true

[package.metadata.docs.rs]
targets = [ "x86_64-apple-darwin",]
