name: clippy

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - master

jobs:
  Lint:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type != 'tag' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Rust linting tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run full pedantic clippy lints
        run: cargo clippy --tests --workspace -- -Dclippy::all -Dclippy::pedantic -D warnings
