on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:

name: tests

env:
  RELEASE_COMMIT: ${{ github.ref_type == 'tag' }}
  PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}

jobs:
  build_universal:
    name: Run non-fat tests on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build x86_64 (Debug)
        if: ${{ env.RELEASE_COMMIT != 'true' }}
        run: cargo build

      - name: Run tests
        run: .github/workflows/run_tests.sh ${{ github.workspace }}/target/debug/alfred-pinboard-rs
